#!/usr/bin/env python

import sys

from rqt_cylinder_counter.my_module import MyPlugin
from rqt_gui.main import Main

plugin = 'rqt_cylinder_counter'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
